import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Đăng ký",
  description: "Generated by create next app",
};

const DangkyLayout = ({ children }: { children: React.ReactNode }) => {
  return <main className="h-full">{children}</main>;
};

export default DangkyLayout;
